Fix user account email
sul-dlss-labs/Vitro pull request #3
Opened 2018-05-15 17:45 UTC by mjgiarlo

* Use TLS for SMTP (necessary for smtp.stanford.edu)
* Get base URL for account emails from config if present, else get from request: this is required in our setup where Tomcat is running behind an Apache HTTP proxy. Without this change, user account emails are sent to users with links back to localhost:8080. Instead override this value in the main Vitro settings XML.

2018-05-15 18:46 UTC, jgreben requested changes
I didn't know you could get the vitro configuration properties this way. Cool! Perhaps making the `mail.smtp.starttls.enable` value configurable in the same way would make this change something more adoptable by community? Either way, this change still looks good as-is.

2018-05-15 19:28 UTC, mjgiarlo commented
@jgreben Oh, I love that. Let me work on that and push up my changes later today.

2018-05-15 19:29 UTC, mjgiarlo commented
@jgreben I will also look into test suite changes related to these tweaks.

2018-05-15 23:13 UTC, mjgiarlo commented
@jgreben I've made the change you asked about.

2018-05-16 04:14 UTC, jgreben approved these changes

2018-05-16 15:39 UTC, merged